crud101/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from viewflow.contrib.admin import Admin
from viewflow.contrib.auth import AuthViewset
from viewflow.urls import Site, Application
from ..atlas.viewset import AtlasApp
from ..staff.urls import StaffApp
from ..tasks.viewsets import (
    TaskViewset,
    ProjectViewset,
    CategoryViewset,
    SubCategoryViewset,
)
from ..sales.urls import SalesApp

site = Site(
    title="CRUD 101 Demo",
    primary_color="#3949ab",
    secondary_color="#5c6bc0",
    viewsets=[
        AtlasApp(),
        StaffApp(),
        Application(
            app_name="tasks",
            title="Tasks",
            icon="tasks",
            viewsets=[
                CategoryViewset(),
                SubCategoryViewset(),
                ProjectViewset(),
                TaskViewset(),
            ],
        ),
        SalesApp(),
        Admin(),
    ],
)

urlpatterns = [
    path("", site.urls),
    path("accounts/", AuthViewset().urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crud101/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]


# TODO polls = Application()

crud101/staff/urls.py
from viewflow import Icon
from viewflow.urls import Application
from . import viewset


class StaffApp(Application):
    title = 'Staff Management'
    icon = Icon('groups')
    permission=lambda user: user.is_staff,
    viewsets = [
        viewset.DepartmentViewset(),
        viewset.EmployeeViewset()
    ]

crud101/staff/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from .managers import TemporalQuerySet


class Department(models.Model):
    dept_no = models.CharField(_('code'), primary_key=True, max_length=4)
    dept_name = models.CharField(_('name'), unique=True, max_length=40)

    class Meta:
        verbose_name = _('department')
        verbose_name_plural = _('departments')
        db_table = 'departments'
        ordering = ['dept_no']

    def __str__(self):
        return self.dept_name


class DeptEmp(models.Model):
    employee = models.ForeignKey('Employee', on_delete=models.CASCADE, db_column='emp_no', verbose_name=_('employee'))
    department = models.ForeignKey(Department, on_delete=models.CASCADE, db_column='dept_no', verbose_name=_('department'))
    from_date = models.DateField(_('from'))
    to_date = models.DateField(_('to'))

    objects = TemporalQuerySet.as_manager()

    class Meta:
        verbose_name = _('department employee')
        verbose_name_plural = _('department employees')
        db_table = 'dept_emp'

    def __str__(self):
        return "{} - {}".format(self.employee, self.department)


class DeptManager(models.Model):
    employee = models.ForeignKey('Employee', on_delete=models.CASCADE, db_column='emp_no', verbose_name=_('employee'))
    department = models.ForeignKey(Department, on_delete=models.CASCADE, db_column='dept_no', verbose_name=_('department'))
    from_date = models.DateField(_('from'))
    to_date = models.DateField(_('to'))

    objects = TemporalQuerySet.as_manager()

    class Meta:
        verbose_name = _('department manager')
        verbose_name_plural = _('department managers')
        db_table = 'dept_manager'
        ordering = ['-from_date']

    def __str__(self):
        return "{} - {}".format(self.employee, self.department)


class Employee(models.Model):
    emp_no = models.IntegerField(_('employee number'), primary_key=True)
    birth_date = models.DateField(_('birthday'))
    first_name = models.CharField(_('first name'), max_length=14)
    last_name = models.CharField(_('last name'), max_length=16)
    gender = models.CharField(_('gender'), max_length=1)
    hire_date = models.DateField(_('hire date'))

    class Meta:
        verbose_name = _('employee')
        verbose_name_plural = _('employees')
        db_table = 'employees'

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)


class Salary(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, db_column='emp_no', verbose_name=_('employee'))
    salary = models.IntegerField(_('salary'))
    from_date = models.DateField(_('from'))
    to_date = models.DateField(_('to'))

    objects = TemporalQuerySet.as_manager()

    class Meta:
        db_table = 'salaries'
        ordering = ['-from_date']
        verbose_name = _('salary')
        verbose_name_plural = _('salaries')

    def __str__(self):
        return "{} - {}".format(self.employee, self.salary)


class Title(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, db_column='emp_no', verbose_name=_('employee'))
    title = models.CharField(_('title'), max_length=50)
    from_date = models.DateField(_('from'))
    to_date = models.DateField(_('to'), blank=True, null=True)

    objects = TemporalQuerySet.as_manager()

    class Meta:
        verbose_name = _('title')
        verbose_name_plural = _('titles')
        db_table = 'titles'

    def __str__(self):
        return "{} - {}".format(self.employee, self.title)

crud101/staff/forms.py
from django import forms
from django.db.models import Value
from django.db.models.functions import Concat
from django.utils.translation import gettext_lazy as _
from viewflow.forms import AjaxModelSelect

from .models import Department, Employee, DeptManager, DeptEmp, Title, Salary


class UpdateDepartmentForm(forms.ModelForm):
    dept_no = forms.CharField(disabled=True)

    class Meta:
        model = Department
        fields = '__all__'


class UpdateEmployeeForm(forms.ModelForm):
    emp_no = forms.CharField(disabled=True)

    class Meta:
        model = Employee
        fields = '__all__'


class ChangeManagerForm(forms.Form):
    manager = forms.ModelChoiceField(
        queryset=Employee.objects.annotate(
            full_name=Concat('first_name', Value(' '), 'last_name')
        ).all(),
        label=_('Manager'),
        help_text=_('full name'),
        widget=AjaxModelSelect(lookups=['full_name__icontains']))

    def __init__(self, *args, **kwargs):
        self.department = kwargs.pop('department')
        super(ChangeManagerForm, self).__init__(*args, **kwargs)

    def save(self):
        new_manager = self.cleaned_data['manager']

        DeptManager.objects.filter(
            department=self.department
        ).set(
            department=self.department,
            employee=new_manager
        )


class ChangeDepartmentForm(forms.Form):
    department = forms.ModelChoiceField(
        queryset=Department.objects.all(),
        label=_('Change department'))

    def __init__(self, *args, **kwargs):
        self.employee = kwargs.pop('employee')
        super(ChangeDepartmentForm, self).__init__(*args, **kwargs)

    def save(self):
        new_department = self.cleaned_data['department']

        DeptEmp.objects.filter(
            employee=self.employee
        ).set(
            department=new_department,
            employee=self.employee
        )


class ChangeTitleForm(forms.Form):
    position = forms.CharField(label=_('Position'))

    def __init__(self, *args, **kwargs):
        self.employee = kwargs.pop('employee')
        super(ChangeTitleForm, self).__init__(*args, **kwargs)

    def save(self):
        new_title = self.cleaned_data['position']

        Title.objects.filter(
            employee=self.employee,
        ).set(
            employee=self.employee,
            title=new_title
        )


class ChangeSalaryForm(forms.Form):
    salary = forms.IntegerField(max_value=1000000, label=_('Salary'))

    def __init__(self, *args, **kwargs):
        self.employee = kwargs.pop('employee')
        super(ChangeSalaryForm, self).__init__(*args, **kwargs)

    def save(self):
        new_salary = self.cleaned_data['salary']

        Salary.objects.filter(
            employee=self.employee,
        ).set(
            employee=self.employee,
            salary=new_salary,
        )

crud101/staff/views.py
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.decorators import permission_required
from django.http import JsonResponse, QueryDict
from django.shortcuts import get_object_or_404, render, redirect
from viewflow.forms import get_ajax_suggestions
from viewflow.views import ListModelView

from .models import Department, Employee, DeptEmp
from .forms import ChangeManagerForm, ChangeSalaryForm, ChangeTitleForm, ChangeDepartmentForm


@permission_required("employees.change_deptmanager")
def change_manager(request, pk):
    department = get_object_or_404(Department, pk=pk)
    form = ChangeManagerForm(department=department, data=request.POST or None)

    if request.method == "OPTIONS":
        query = request.META.get('HTTP_X_REQUEST_AUTOCOMPLETE', request.body)
        options = QueryDict(query, encoding=request.encoding)
        field = form.base_fields.get(options.get("field"))
        query = options.get("query")
        if field is None or query is None:
            return JsonResponse({"error": "Field or Query is missing"}, status=400)
        return JsonResponse({"suggestions": get_ajax_suggestions(field, query)})
    elif request.method == "POST" and form.is_valid():
        form.save()
        return redirect(f"{request.resolver_match.namespace}:detail", department.pk)

    return render(request, "staff/manager_change.html", {
        "form": form,
        "department": department,
        "model": Department
    })


@permission_required("employees.change_salary")
def change_salary(request, pk):
    employee = get_object_or_404(Employee, pk=pk)
    form = ChangeSalaryForm(employee=employee, data=request.POST or None)

    if form.is_valid():
        form.save()
        return redirect(f"{request.resolver_match.namespace}:detail", employee.pk)

    return render(request, 'staff/salary_change.html', {
        'form': form,
        'employee': employee,
    })


@permission_required("employees.change_title")
def change_title(request, pk):
    employee = get_object_or_404(Employee, pk=pk)
    form = ChangeTitleForm(employee=employee, data=request.POST or None)

    if form.is_valid():
        form.save()
        return redirect(f"{request.resolver_match.namespace}:detail", employee.pk)

    return render(request, 'staff/title_change.html', {
        'form': form,
        'employee': employee,
    })


@permission_required('employees.change_deptemp')
def change_department(request, pk):
    employee = get_object_or_404(Employee, pk=pk)
    form = ChangeDepartmentForm(employee=employee, data=request.POST or None)

    if form.is_valid():
        form.save()
        return redirect(f"{request.resolver_match.namespace}:detail", employee.pk)

    return render(request, 'staff/employee_department_change.html', {
        'form': form,
        'employee': employee,
    })


class DepartmentEmployeesListView(ListModelView):
    model = Employee
    columns = ('emp_no', 'first_name', 'last_name', 'works_since', 'birth_date')
    template_name = 'staff/department_employees_list.html'

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.department = get_object_or_404(Department, pk=self.kwargs.get('pk', -1))

    def get_queryset(self):
        today = timezone.now().date()
        queryset = super().get_queryset()
        return queryset.filter(
            deptemp__department=self.department,
            deptemp__from_date__lte=today,
            deptemp__to_date__gt=today
        )

    def works_since(self, obj):
        return DeptEmp.objects.filter(employee=obj).current().from_date

    def get_object_url(self, obj):
        return reverse('staff:employee:detail', args=[obj.pk])

crud101/staff/templates/staff/includes/department_detail_card.html
{% extends 'viewflow/includes/object_detail_card.html' %}
{% load i18n viewflow %}


{% block detail-extra %}
<tr>
  <th class="vf-list__table-header vf-list__table-header-text">{% trans 'Employees' %}</th>
  <td class="vf-list__table-cell vf-list__table-cell-text">
    <a href="{% reverse viewset 'employees' object.pk %}">
      {{ object.deptemp_set.count }}
    </a>
  </td>
</tr>
{% endblock %}

crud101/staff/templates/staff/includes/department_managers_card.html
{% load i18n humanize viewflow %}
<div class="mdc-card vf-card">
  <section class="vf-card__header">
    <h1 class="vf-card__title">{% trans 'Department Managers' %}</h1>
  </section>
  <section class="mdc-data-table">
    <div class="mdc-data-table__table-container">
      <table class="mdc-data-table__table">
        <thead>
          <tr class="mdc-data-table__header-row">
            <td class="mdc-data-table__header-cell">{% trans 'Manager' %}</td>
            <td class="mdc-data-table__header-cell">{% trans 'Since' %}</td>
          </tr>
        </thead>
        <tbody class="mdc-data-table__content">
          {% for manager in object.deptmanager_set.all %}
          <tr class="mdc-data-table__row">
            <td class="mdc-data-table__cell">
                <a href="{% url 'staff:employee:detail' manager.employee.pk %}">{{ manager.employee }}</a>
            </td>
            <td class="mdc-data-table__cell">{{ manager.from_date }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </section>
  <section class="mdc-card__actions vf-card__actions">
    <a class="mdc-button mdc-card__action mdc-card__action--button" href="{% reverse viewset 'change_manager' object.pk %}">{% trans 'Change' %}</a>
  </section>
</div>

crud101/staff/templates/staff/includes/employee_departments_card.html
{% load i18n humanize viewflow %}
<div class="mdc-card vf-card">
  <section class="vf-card__header">
    <h1 class="vf-card__title">{% trans 'Departments' %}</h1>
  </section>
  <section class="mdc-data-table">
    <div class="mdc-data-table__table-container">
      <table class="mdc-data-table__table">
        <thead>
          <tr class="mdc-data-table__header-row">
            <td class="mdc-data-table__header-cell">{% trans 'Department' %}</td>
            <td class="mdc-data-table__header-cell">{% trans 'Since' %}</td>
            <td class="mdc-data-table__header-cell">{% trans 'To' %}</td>
          </tr>
        </thead>
        <tbody class="mdc-data-table__content">
          {% for dept in object.deptemp_set.all|slice:":10" %}
          <tr class="mdc-data-table__row">
            <td class="mdc-data-table__cell">{{ dept.department }}</td>
            <td class="mdc-data-table__cell">{{ dept.from_date }}</td>
            <td class="mdc-data-table__cell">{{ dept.to_date }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </section>
  <section class="mdc-card__actions vf-card__actions">
      <a class="mdc-button mdc-card__action mdc-card__action--button" href="{% reverse viewset 'change_department' object.pk %}">{% trans 'Change' %}</a>
  </section>
</div>

crud101/staff/templates/staff/includes/employee_positions_card.html
{% load i18n humanize viewflow %}
<div class="mdc-card vf-card">
  <section class="vf-card__header">
    <h1 class="vf-card__title">{% trans 'Positions' %}</h1>
  </section>
  <section class="mdc-data-table">
    <div class="mdc-data-table__table-container">
      <table class="mdc-data-table__table">
        <thead>
          <tr class="mdc-data-table__header-row">
            <td class="mdc-data-table__header-cell">{% trans 'Position' %}</td>
            <td class="mdc-data-table__header-cell">{% trans 'Since' %}</td>
            <td class="mdc-data-table__header-cell">{% trans 'To' %}</td>
          </tr>
        </thead>
        <tbody class="mdc-data-table__content">
          {% for title in object.title_set.all|slice:":10" %}
          <tr class="mdc-data-table__row">
            <td class="mdc-data-table__cell">{{ title.title }}</td>
            <td class="mdc-data-table__cell">{{ title.from_date }}</td>
            <td class="mdc-data-table__cell">{{ title.to_date }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </section>
  <section class="mdc-card__actions vf-card__actions">
      <a class="mdc-button mdc-card__action mdc-card__action--button" href="{% reverse viewset 'change_title' object.pk %}">{% trans 'Change' %}</a>
  </section>
</div>

crud101/staff/templates/staff/includes/employee_salary_card.html
{% load viewflow i18n humanize %}
<div class="mdc-card vf-card">
  <section class="vf-card__header">
    <h1 class="vf-card__title">{% trans 'Salary' %}</h1>
  </section>
  <section class="mdc-data-table">
    <div class="mdc-data-table__table-container">
      <table class="mdc-data-table__table">
        <thead>
          <tr class="mdc-data-table__header-row">
            <td class="mdc-data-table__header-cell">{% trans 'Salary' %}</td>
            <td class="mdc-data-table__header-cell">{% trans 'Since' %}</td>
          </tr>
        </thead>
        <tbody class="mdc-data-table__content">
          {% for salary in object.salary_set.all|slice:":10" %}
          <tr class="mdc-data-table__row">
            <td class="mdc-data-table__cell">${{ salary.salary|intcomma }}</td>
            <td class="mdc-data-table__cell">{{ salary.from_date }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </section>
  <section class="mdc-card__actions vf-card__actions">
      <a class="mdc-button mdc-card__action mdc-card__action--button" href="{% reverse viewset 'change_salary' object.pk %}">{% trans 'Change' %}</a>
  </section>
</div>