workflow101/config/urls.py
from django.contrib import admin
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.views.generic import TemplateView
from django.shortcuts import redirect
from django.urls import path, include

from viewflow.contrib.auth import AuthViewset
from viewflow.urls import Application, Site
from viewflow.workflow.flow import FlowAppViewset

from ..bloodtest.flows import BloodTestFlow
from ..dynamic_split.flows import DynamicSplitFlow
from ..helloworld.flows import HelloWorldFlow
from ..reassign.flows import ReassignFlow
from ..shipment.flows import ShipmentFlow
from ..shipment.viewsets import ShipmentViewset, CarierViewset
from ..subprocesses.flows import OrderItemFlow, CustomerVerificationFlow, OrderFlow

site = Site(
    title="Workflow 101 Demo",
    viewsets=[
        Application(
            app_name="intro",
            icon="account_balance",
            title="Introduction",
            menu_template_name=None,
            urlpatterns=[
                path(
                    "",
                    TemplateView.as_view(template_name="workflow101/index.html"),
                    name="index",
                ),
            ],
        ),
        FlowAppViewset(HelloWorldFlow, icon="assignment"),
        FlowAppViewset(DynamicSplitFlow, icon="call_split"),
        FlowAppViewset(BloodTestFlow, icon="bloodtype"),
        FlowAppViewset(ReassignFlow, icon="swap_horiz"),
        Site(
            app_name="subprocess",
            title="Orders processing",
            icon="account_tree",
            permission="view_orderprocess",
            primary_color="#d20011",
            viewsets=[
                FlowAppViewset(OrderFlow, icon="shopping_cart"),
                FlowAppViewset(CustomerVerificationFlow, icon="hail"),
                FlowAppViewset(OrderItemFlow, icon="toc"),
                FlowAppViewset(
                    ShipmentFlow,
                    icon="local_shipping",
                    viewsets=[
                        CarierViewset(),
                        ShipmentViewset(),
                    ],
                ),
            ],
        ),
    ],
)


def users(request):
    return {"users": User.objects.filter(is_active=True).order_by("-username")}


def login_as(request):
    try:
        user = User.objects.get(username=request.GET.get("username"))
    except User.DoesNotExist:
        pass
    else:
        user.backend = "django.contrib.auth.backends.ModelBackend"
        login(request, user)
    return redirect("/")


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", AuthViewset().urls),
    path("login_as/", login_as, name="login_as"),
    path("", include("cookbook.workflow101.hellorest.urls")),
    path("", site.urls),
]

workflow101/shipment/models.py
from django.db import models
from viewflow.workflow.models import Process


class Carrier(models.Model):
    DEFAULT = "Default"

    name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)

    def is_default(self):
        return self.name == Carrier.DEFAULT

    def __str__(self):
        return self.name


class Insurance(models.Model):
    company_name = models.CharField(max_length=50)
    cost = models.IntegerField()

    def __str__(self):
        return "{} ${}".format(self.company_name, self.cost)


class Shipment(models.Model):
    shipment_no = models.CharField(max_length=50)
    carrier = models.ForeignKey(Carrier, null=True, on_delete=models.CASCADE)

    # customer
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.EmailField()

    # shipment address
    address = models.CharField(max_length=150)
    city = models.CharField(max_length=150)
    state = models.CharField(max_length=150)
    zipcode = models.CharField(max_length=10)
    country = models.CharField(max_length=150)
    phone = models.CharField(max_length=50)

    # shipment data
    need_insurance = models.BooleanField(default=False)
    insurance = models.ForeignKey("Insurance", null=True, on_delete=models.CASCADE)

    carrier_quote = models.IntegerField(default=0)
    post_label = models.TextField(blank=True, null=True)

    package_tag = models.CharField(max_length=50)

    def __str__(self):
        if self.pk:
            return f"#{self.shipment_no} {self.last_name} {self.first_name}/{self.city}"
        return super().__str__()


class ShipmentItem(models.Model):
    shipment = models.ForeignKey(Shipment, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    quantity = models.IntegerField(default=1)


class ShipmentProcess(Process):
    class Meta:
        proxy = True
        verbose_name_plural = "Shipment process list"
        permissions = [
            ("can_start_request", "Can start shipment request"),
            ("can_take_extra_insurance", "Can take extra insurance"),
            ("can_package_goods", "Can package goods"),
            ("can_move_package", "Can move package"),
        ]

    @property
    def created_by(self):
        """Lookup for the owner of the task that started the flow."""
        return self.flow_class.task_class._default_manager.get(
            process=self, flow_task_type="HUMAN_START"
        ).owner

    def is_normal_post(self):
        try:
            if self.artifact.carrier:
                return self.artifact.carrier.is_default()
            else:
                return None
        except (Shipment.DoesNotExist, Carrier.DoesNotExist):
            return None

    def need_extra_insurance(self):
        try:
            return self.artifact.need_insurance
        except Shipment.DoesNotExist:
            return None

workflow101/shipment/forms.py
from django import forms
from viewflow.forms import (
    ModelForm,
    InlineFormSetField,
    Layout,
    FieldSet,
    Row,
    Span,
    Tag,
    TotalCounterWidget,
)


from .models import Shipment, ShipmentItem


class ShipmentForm(ModelForm):
    items = InlineFormSetField(
        Shipment,
        ShipmentItem,
        fields=["name", "quantity"],
        can_delete=False,
        extra=1,
    )
    total = forms.CharField(
        widget=TotalCounterWidget(expression="sum(items.quantity)"), label=""
    )

    layout = Layout(
        Row("shipment_no"),
        FieldSet(
            "Customer Details", Row("first_name", "last_name", "email"), Row("phone")
        ),
        FieldSet(
            "Address",
            Row(Span("address", desktop=7), Span("zipcode", desktop=5)),
            Row(
                Span("city", desktop=5),
                Span("state", desktop=2),
                Span("country", desktop=5),
            ),
        ),
        "items",
        Row(
            Tag(
                "h4",
                text="Total:",
                style="text-align:right",
                class_="mdc-typography",
            ),
            "total",
        ),
    )

    class Meta:
        model = Shipment
        fields = [
            "shipment_no",
            "first_name",
            "last_name",
            "email",
            "phone",
            "address",
            "zipcode",
            "city",
            "state",
            "country",
        ]

workflow101/shipment/views.py
from django.http import HttpResponseRedirect
from django.views import generic
from viewflow.workflow.flow.views import TaskSuccessUrlMixin

from .forms import ShipmentForm
from .models import Insurance


class StartView(TaskSuccessUrlMixin, generic.CreateView):
    form_class = ShipmentForm
    template_name = 'viewflow/workflow/start.html'

    def form_valid(self, form):
        self.object = form.save()

        self.request.activation.process.artifact = self.object

        self.request.activation.execute()
        return HttpResponseRedirect(self.get_success_url())


class ShipmentView(TaskSuccessUrlMixin, generic.UpdateView):
    template_name = 'viewflow/workflow/task.html'

    def get_object(self):
        return self.request.activation.process.artifact

    def form_valid(self, form):
        self.object = form.save()

        self.request.activation.process.artifact = self.object

        self.request.activation.execute()
        return HttpResponseRedirect(self.get_success_url())


class InsuranceView(TaskSuccessUrlMixin, generic.CreateView):
    model = Insurance
    template_name = 'viewflow/workflow/task.html'
    fields = ["company_name", "cost"]

    def form_valid(self, form):
        self.object = form.save()

        shipment = self.request.activation.process.artifact
        shipment.insurance = self.object
        shipment.save(update_fields=["insurance"])

        self.request.activation.execute()
        return HttpResponseRedirect(self.get_success_url())

workflow101/shipment/templates/shipment/shipment/process_data.html
{% load viewflow %}
{% if process.pk %}
{% with process.artifact as shipment %}
<div class="mdc-layout-grid" style="padding:0px">
  <div class="mdc-layout-grid__inner" style="grid-gap: 16px">
    <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12">
      <div class="mdc-card vf-card">
        <section class="vf-card__header">
          <h1 class="vf-card__title">Shipment #{{ shipment.shipment_no }}
            <small>{% if perms.shipment.change_shipment %}
              <a href="{% url 'admin:shipment_shipment_change' shipment.pk as url %}" class="card-edit no-pjax" target="_blank">(edit)</a>
            {% endif %}</small>
          </h1>
        </section>
        <section class="vf-card__body">
          <table class="vf-list__table">
            <tbody>
              <tr>
                <td colspan="2">
                  <vf-modal-trigger class="vf-modal-trigger--closed">
                    <span class="vf-modal-trigger__helper"></span>
                    <div class="vf-modal-trigger__content">
                      <div class="vf-modal-trigger__button">&times;</div>
                      <vf-img>
                        <img class="responsive-img" src="{% reverse process.flow_class 'process_chart' process.pk %}" alt="flow graph" style="height:100%;max-width:100%"/>
                      </vf-img>
                    </div>
                  </vf-modal-trigger>
                </td>
              </tr>
              <tr>
                <th>Item</th>
                <th>Count</th>
              </tr>
                {% for item in shipment.shipmentitem_set.all %}
              <tr>
                  <td> {{ item.name }} </td>
                  <td> {{ item.quantity }} </td>
              </tr>
              {% empty %}
              <tr>
                  <td colspan="2">No items in shipment</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </section>
      </div>
    </div>
    <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12">
      <div class="mdc-card vf-card">
        <section class="vf-card__header">
          <h4 class="vf-card__title">Address</h4>
        </section>
        <section class="vf-card__body mdc-typography" style="margin:0px 16px 16px 16px">
          {{ shipment.zipcode }}, {{ shipment.country }}, {{ shipment.city }}, {{ shipment.state }}<br/>
          {{ shipment.address }} <br/><br/>
          <strong>Phone:</strong> {{ shipment.phone }}
        </section>
      </div>
    </div>

    {% if shipment.carrier or shipment.insurance %}
    <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12">
      <div class="mdc-card vf-card">
        <section class="vf-card__header">
          <h4 class="vf-card__title">Delivery</h4>
        </section>
        <section class="vf-card__body mdc-typography" style="margin:0px 16px 16px 16px">
          <strong>Carrier:</strong> {{ shipment.carrier.name }}
          {% if perms.shipment.change_carrier %}
              <a href="{% url 'admin:shipment_carrier_change' shipment.carrier.pk %}" class="no-pjax" target="_blank">(edit)</a>
          {% endif %}
          <br/>
          {% endif %}
          {% if shipment.insurance %}
          <strong>Insurance:</strong> {{ shipment.insurance.company_name }} {{ shipment.insurance.cost}}
          {% if perms.shipment.change_insurance %}
              <a href="{% url 'admin:shipment_insurance_change' shipment.insurance.pk %}" class="no-pjax" target="_blank">(edit)</a>
          {% endif %}
        </section>
      </div>
    </div>
    {% endif %}
  </div>
</div>
{% endwith %}
{% endif %}